include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    #  Clean Code Rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    prefer_final_fields: true
    prefer_final_locals: true

    always_declare_return_types: true
    unnecessary_this: true
    sort_child_properties_last: true
    use_super_parameters: true

    #  Bad practices prevention
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true

    #  Code readability
    prefer_single_quotes: true
    directives_ordering: true